inveniosoftware/invenio-oauth2server

CHANGES.rst, MANIFEST.in, RELEASE-NOTES.rst, invenio_oauth2server/version.py
=> Invenio-OAuth2Server v0.1.0

AUTHORS.rst, CHANGES.rst, MANIFEST.in, RELEASE-NOTES.rst, invenio_oauth2server/translations/de/LC_MESSAGES/messages.po, invenio_oauth2server/translations/es/LC_MESSAGES/messages.po, invenio_oauth2server/translations/fr/LC_MESSAGES/messages.po, invenio_oauth2server/translations/invenio.pot, invenio_oauth2server/translations/it/LC_MESSAGES/messages.po, invenio_oauth2server/version.py, setup.cfg
=> Invenio-OAuth2Server v0.1.1

invenio_oauth2server/upgrades/oauth2server_2015_07_14_innodb.py
Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
=> upgrader: better dependencies

invenio_oauth2server/forms.py, invenio_oauth2server/models.py, invenio_oauth2server/views/server.py, invenio_oauth2server/views/settings.py, requirements-devel.txt, setup.py, tests/test_provider.py
* FIX Adds missing `invenio_base` dependency and amends past
upgrade recipes following its separation into standalone package.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> installation: fix invenio_base imports

invenio_oauth2server/forms.py, invenio_oauth2server/models.py, invenio_oauth2server/provider.py, invenio_oauth2server/upgrades/oauth2server_2014_02_17_initial.py, invenio_oauth2server/upgrades/oauth2server_2015_07_14_innodb.py, invenio_oauth2server/views/server.py, invenio_oauth2server/views/settings.py, requirements-devel.txt, setup.py, tests/test_models.py, tests/test_provider.py
=> global : fix invenio_utils imports

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py, setup.py, tests/test_provider.py
=> Invenio-OAuth2Server v0.2.0

invenio_oauth2server/__init__.py, invenio_oauth2server/decorators.py, invenio_oauth2server/version.py, tests/conftest.py, tests/test_decorators.py
* Ports decorators from legacy Invenio RESTFul extension.
=> global: decorators for authentication

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
=> release: v1.0.0a1

.travis.yml, examples/app.py, invenio_oauth2server/config.py, invenio_oauth2server/ext.py, invenio_oauth2server/forms.py, invenio_oauth2server/models.py, invenio_oauth2server/provider.py, invenio_oauth2server/templates/invenio_oauth2server/settings/client_view.html, invenio_oauth2server/views/server.py, invenio_oauth2server/views/settings.py, setup.py, tests/conftest.py, tests/test_invenio_oauth2server.py, tests/test_models.py, tests/test_provider.py, tests/test_settings.py, tests/test_validators.py
* Adds more tests to increase the coverage of tests.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> tests: improvements to test coverage

invenio_oauth2server/ext.py, invenio_oauth2server/templates/invenio_oauth2server/settings/_macros.html, invenio_oauth2server/templates/invenio_oauth2server/settings/base.html, invenio_oauth2server/templates/invenio_oauth2server/settings/client_new.html, invenio_oauth2server/templates/invenio_oauth2server/settings/client_view.html, invenio_oauth2server/templates/invenio_oauth2server/settings/index.html, invenio_oauth2server/templates/invenio_oauth2server/settings/token_new.html, invenio_oauth2server/templates/invenio_oauth2server/settings/token_view.html, tests/test_invenio_oauth2server.py, tests/test_models.py, tests/test_settings.py
* Fixes issues with template block names causing rendering issues when used
together with Invenio-Theme.
=> templates: block fixes

invenio_oauth2server/views/settings.py
=> views: menu highlighting fix

.gitignore, MANIFEST.in, examples/app.py, examples/requirements.txt, invenio_oauth2server/views/settings.py
=> view: fix token creation

examples/app.py, invenio_oauth2server/decorators.py, tests/test_decorators.py
=> WIP decorators: authorization requirement improvement

setup.py, tests/conftest.py, tests/test_decorators.py
=> tests: login_required testsuite addition

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py, setup.py, tests/conftest.py, tests/test_decorators.py
=> release: v1.0.0a2

invenio_oauth2server/version.py
=> version: post-release bump

invenio_oauth2server/decorators.py, tests/conftest.py, tests/test_decorators.py
--
addresses inveniosoftware/invenio-records-rest#81
=> decorators: new allow_anonymous option

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
=> release: v1.0.0a4

invenio_oauth2server/__init__.py, invenio_oauth2server/ext.py, setup.py, tests/conftest.py, tests/test_decorators.py, tests/test_invenio_oauth2server.py
=> ext: automatic OAuth token validator

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
=> release: v1.0.0a5

CHANGES.rst, RELEASE-NOTES.rst, docs/conf.py, invenio_oauth2server/decorators.py, invenio_oauth2server/ext.py, invenio_oauth2server/utils.py, invenio_oauth2server/version.py, invenio_oauth2server/views/server.py, tests/conftest.py, tests/test_decorators.py, tests/test_provider.py
* Fixes issue with oauthlib's urldecoding which chokes on e.g. colons.
=> global: oauthlib url decoding fix

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
=> release: v1.0.0a7

invenio_oauth2server/ext.py
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> ext: set request.oauth for REST requests

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/ext.py, invenio_oauth2server/version.py, invenio_oauth2server/views/server.py
* Fixes issue with ``request.oauth`` being set for invalid requests.
=> ext: rest requests fix

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> release: v1.0.0a9

examples/app.py, setup.py, tests/conftest.py
* Removes dependency on Flask-CLI.
=> installation: Flask>=0.11

examples/app.py, setup.py, tests/conftest.py
* Initializes the InvenioOAuth2ServerREST extension when the example
application is created. (closes #62)
Signed-off-by: PaulinaLach <paulina.malgorzata.lach@cern.ch>
=> example: intialization of InvenioOAuth2ServerREST

.travis.yml, setup.py, tests/conftest.py, tests/test_decorators.py
- pins oauthlib<2.0.0
- amends tests using login_required (kudos @slint)
=> global: OAuth fixes

.tx/config, MANIFEST.in, README.rst, RELEASE-NOTES.rst, docs/requirements.txt
=> docs: move to readthedocs.io

.lgtm, .tx/config, MAINTAINERS, MANIFEST.in, README.rst, RELEASE-NOTES.rst, docs/requirements.txt
=> docs: MAINTAINERS file and LGTM configuration

docs/api.rst, invenio_oauth2server/config.py, invenio_oauth2server/ext.py, invenio_oauth2server/forms.py, tests/test_invenio_oauth2server.py
- adds API autodoc (addresses #57)
=> global: package style and initialization

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> release: v1.0.0a11

invenio_oauth2server/decorators.py, invenio_oauth2server/ext.py, invenio_oauth2server/views/server.py, setup.py, tests/helpers.py, tests/test_decorators.py
Signed-off-by: David Caro <david@dcaro.es>
=> packaging: use flask-security-fork

docs/conf.py, invenio_oauth2server/config.py, invenio_oauth2server/decorators.py, invenio_oauth2server/ext.py, invenio_oauth2server/models.py, invenio_oauth2server/provider.py, invenio_oauth2server/proxies.py, invenio_oauth2server/validators.py, invenio_oauth2server/views/settings.py, setup.py, tests/test_provider.py
- Improves documentation. (addresses #57)
Signed-off-by: Leonardo Rossi leonardo.r@cern.ch
=> docs: addition of param and result sections

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
=> release: v1.0.0a13

requirements-devel.txt, setup.py
* Adds development repositories of OAuthLib and Flask-OAuthLib for
early detection of possible dependency issues.  (closes #78)
=> installation: unpinned OAuthLib

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> release: v1.0.0a14

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
=> release: v1.0.0a15

invenio_oauth2server/templates/invenio_oauth2server/authorize.html
=> templates: minor style fixes

invenio_oauth2server/utils.py, requirements-devel.txt, setup.py, tests/test_utils.py
=> entry point function for SECRET_KEY change

CHANGES.rst, RELEASE-NOTES.rst, invenio_oauth2server/version.py
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
=> release: 1.0.0a16

invenio_oauth2server/ext.py, invenio_oauth2server/provider.py, tests/conftest.py, tests/test_provider.py
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> global: user deactivation prevents OAuth authentication.

docs/examplesapp.rst, examples/app.py, invenio_oauth2server/ext.py, invenio_oauth2server/signals.py, invenio_oauth2server/templates/invenio_oauth2server/settings/client_view.html, invenio_oauth2server/utils.py, invenio_oauth2server/views/server.py, tests/test_decorators.py
* ADDS custom save session to disable cookies
when login attempted via headers.
(unblocks https://github.com/inveniosoftware/invenio-oauth2server/pull/128 https://github.com/inveniosoftware/invenio-oauth2server/pull/126)
Co-authored-by: Harris Tzovanakis <me@drjova.com>
=> ext: custom save session

MANIFEST.in, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, invenio_oauth2server/admin.py, invenio_oauth2server/alembic/4e57407b8e4a_add_on_delete_cascade.py, invenio_oauth2server/alembic/6843f5996f26_add_on_delete_cascade.py, invenio_oauth2server/models.py, setup.py
Authored-by: David Caro <david@dcaro.es>
Co-authored-by: Krzysztof Nowak <k.nowak@cern.ch>
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> model: add cascade to all foreign keys

tests/test_admin.py
=> tests: admin interface

invenio_oauth2server/templates/invenio_oauth2server/settings/index.html
* Replaces the old config variable CFG_SITE_NAME with THEME_SITENAME.
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> views: CFG_SITE_NAME config replacement

examples/templates/jwt.html
=> examples: fix jquery load

invenio_oauth2server/ext.py, invenio_oauth2server/templates/invenio_oauth2server/authorize.html
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> templates: use cover template for /oauth/authorize

invenio_oauth2server/templates/invenio_oauth2server/settings/helpers.html
* Prevents CSP errors. (closes inveniosoftware/invenio-app-ils#29)
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>
=> templates: convert inline CSS to ng-style

examples/app.py, invenio_oauth2server/templates/invenio_oauth2server/authorize.html, invenio_oauth2server/views/server.py
* Redesigns the "Authorize application" page to be more clear on who is
the currently logged in user (closes #140).
=> templates: authorize redesign

examples/app.py, invenio_oauth2server/provider.py, invenio_oauth2server/scopes.py, invenio_oauth2server/templates/invenio_oauth2server/authorize.html, invenio_oauth2server/views/server.py, setup.py, tests/conftest.py, tests/test_provider.py
* ADD default scope to return user id and email
with the access token
=> global: default scope

CHANGES.rst, README.rst, RELEASE-NOTES.rst, docs/conf.py, docs/examplesapp.rst, docs/index.rst, examples/app-fixtures.sh, examples/app.py, examples/consumer.py, invenio_oauth2server/alembic/4e57407b8e4a_add_on_delete_cascade.py, invenio_oauth2server/forms.py, invenio_oauth2server/templates/invenio_oauth2server/settings/index.html, invenio_oauth2server/templates/invenio_oauth2server/settings/token_permission_view.html, invenio_oauth2server/validators.py, invenio_oauth2server/version.py, invenio_oauth2server/views/server.py, invenio_oauth2server/views/settings.py, setup.py, tests/test_settings.py, tests/test_validators.py
=> release v1.0.0b1

setup.py, tests/test_utils.py
* Pins the oauthlib package (there is a bug).
* Updates the tests for rebuilding access token.
=> Fixed failing travis builds

invenio_oauth2server/templates/invenio_oauth2server/errors.html
* Add cover template for errors (closes #157)
Signed-off-by: Miltiadis Alexis miltiadis.alexis@cern.ch
=> templates: use cover template for errors

invenio_oauth2server/templates/invenio_oauth2server/authorize.html, invenio_oauth2server/templates/invenio_oauth2server/errors.html
* Style authorize with left align (closes #158)
Signed-off-by: Miltiadis Alexis miltiadis.alexis@cern.ch
=> templates: left align text in authorize

invenio_oauth2server/models.py, invenio_oauth2server/templates/invenio_oauth2server/authorize.html
* Add number of users ( closes #159)
Signed-off-by: Miltiadis Alexis miltiadis.alexis@cern.ch
=> templates: numbers of users in authorise page

invenio_oauth2server/alembic/12a88921ada2_create_oauth2server_tables.py, invenio_oauth2server/models.py, setup.py
Addresses https://github.com/inveniosoftware/invenio-oauth2server/issues/170.
=> global: import EncryptedType correctly

invenio_oauth2server/forms.py, tests/test_settings.py
* Validates the length of the name provided in the TokenForm.
(closes #168)
=> forms: validate length for token form name

docs/requirements.txt
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> docs: added sqlite dependency to docs (invenio-db)

.travis.yml
* ADD deploy condition only for python 2.7, postgresql env
(closes https://github.com/inveniosoftware/invenio-oauth2server/issues/177)
=> travis: add deploy condition

invenio_oauth2server/__init__.py, invenio_oauth2server/config.py, invenio_oauth2server/decorators.py, invenio_oauth2server/ext.py, setup.py
=> global: fix typo in code

docs/conf.py, setup.py
=> docs: flask docs inventory link fix

.travis.yml, CHANGES.rst, invenio_oauth2server/__init__.py, invenio_oauth2server/_compat.py, invenio_oauth2server/ext.py, invenio_oauth2server/version.py, setup.py, tests/conftest.py, tests/helpers.py
=> monkey patch of werkzeug modules (1.0.0) compatibility

CHANGES.rst, invenio_oauth2server/version.py
=> release: v1.3.0a1

invenio_oauth2server/views/settings.py
* Closes https://github.com/inveniosoftware/invenio-oauth2server/issues/213
=> views: fixes scope selectbox missing existing values

invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/helpers.html, run-tests.sh, setup.py, tests/conftest.py, tests/helpers.py, tests/test_alembic.py, tests/test_cli.py, tests/test_invenio_oauth2server.py, tests/test_provider.py
* closes https://github.com/inveniosoftware/invenio-theme/issues/212
=> semantic: harmonize headers

invenio_oauth2server/forms.py, invenio_oauth2server/theme/semantic/form_styling.py, pytest.ini
=> style: add semantic styling to dropdown

CHANGES.rst, invenio_oauth2server/theme/semantic/form_styling.py, invenio_oauth2server/version.py, run-tests.sh
Closes https://github.com/inveniosoftware/invenio-oauth2server/issues/222
Requires https://github.com/inveniosoftware/invenio-theme/pull/225
=> style: comply with defaul semantic ui dropdown

invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/_macros.html
=> forms: fix errors not being rendered

invenio_oauth2server/errors.py
Added the "scope" positional argument needed in newer releases of werkzeug
=> Errors: Werkzeug 2 compatibility fix

babel.ini, invenio_oauth2server/translations/messages.pot
* remove jinja extensions
* update .pot
related inveniosoftware/invenio-app-rdm#1664
=> i18n: extract messages

invenio_oauth2server/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
=> i18n: adds german translations

tests/test_provider.py
- migrate setup.py to setup.cfg
- migrate to use black as opinionated auto formater
- add .git-blame-ignore-revs
- fix docs compatibilty problem with Sphinx>=5.0.0
- move check_manifest configuration to setup.cfg.
- increase minimal python version to 3.7
- global: clean test infrastructure
=> migrate setup and black

invenio_oauth2server/__init__.py, invenio_oauth2server/provider.py
* Change is needed as flask-login==0.6.2 applied that change
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
1. You license your contribution under the same terms as the current …
=> provider: save user in flask.g

invenio_oauth2server/forms.py
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162
=> translations: fix string format

.github/workflows/i18n-pull.yml, .github/workflows/i18n-push.yml, .tx/config, docs/conf.py, tests/conftest.py
ref https://github.com/inveniosoftware/invenio-i18n/issues/114
Migrate transifex config to be compatible with API v3.
Remove i18n workflows, which will be setup on the organization level.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including …
=> transifex: update config

invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/_macros.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/client_new.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/client_view.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/helpers.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/index.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/token_new.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/token_view.html, invenio_oauth2server/theme/semantic/form_styling.py
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2301
=> applications: Improve templates for UI and accessibility

CHANGES.rst, invenio_oauth2server/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
=> release: v2.1.0

CHANGES.rst, invenio_oauth2server/__init__.py
Please describe briefly your pull request.
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
2. You agree that you have the right to license …
=> release: v2.2.0

invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/index.html
fixes https://github.com/zenodo/ops/issues/345
Done with Pamir.
=> ui: settings: fix token scopes list

invenio_oauth2server/templates/invenio_oauth2server/settings/client_view.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/client_view.html
Closes  #261
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> Settings: update page to reflect additional required parameter

invenio_oauth2server/_compat.py, invenio_oauth2server/forms.py, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/_macros.html, invenio_oauth2server/theme/semantic/form_styling.py, invenio_oauth2server/validators.py, setup.cfg
- fix: DeprecationWarning HTMLString
- setup: unpin wtforms dependency
- compatibility: to werkzeug >= 2.3.0
=> remove flask upper pin

CHANGES.rst, invenio_oauth2server/__init__.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you have the right to license …
=> release: v3.0.1

invenio_oauth2server/ext.py
* the problem is that request.form triggers parsing the form. parsing
the form triggers checking the max_content_length. if a file greater
then the allowed filesize is uploaded this raises the
RequestEntityTooLarge exception
* to verify the request the body is not used, the token is used for
verification
=> refactor: copy code from flask-oauthlib-invenio

invenio_oauth2server/theme/semantic/form_styling.py
> Please describe briefly your pull request.
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to license your contribution under the …
=> fix: Update iter_choices to Include Additional Parameter

.github/workflows/tests.yml, CHANGES.rst, invenio_oauth2server/__init__.py, setup.cfg
- ci: add maint tests
- release: v2.5.0
=> rel v2 5 0

invenio_oauth2server/forms.py
Fields in the /account/settings/applications/tokens/new/ don't have labels:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect on Discord](https://discord.gg/8qatqBC).
**Frontend**
**Reminder**
2. You agree that you have the right to …
=> provided translated field labels
