invenio_oauth2server/upgrades/oauth2server_2014_02_17_initial.py, invenio_oauth2server/upgrades/oauth2server_2014_10_21_encrypted_token_columns.py, invenio_oauth2server/upgrades/oauth2server_2015_07_14_innodb.py, requirements-devel.txt, setup.py
* FIX Fixes import of invenio_upgrader in the past upgrade recipes
following its separation into standalone package.
=> global: fix import of invenio_upgrader

examples/app.py, invenio_oauth2server/config.py, invenio_oauth2server/ext.py, invenio_oauth2server/models.py, invenio_oauth2server/provider.py, invenio_oauth2server/templates/invenio_oauth2server/settings/client_view.html, invenio_oauth2server/views/server.py, setup.py, tests/conftest.py, tests/test_invenio_oauth2server.py, tests/test_models.py, tests/test_provider.py
* INCOMPATIBLE Changes the config prefix from OAUTH2 to OAUTH2SERVER.
This is more in line with config prefixes in other Invenio modules.
(closes #19)
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> config: prefix from OAUTH2 to OAUTH2SERVER

invenio_oauth2server/models.py
* Removes custom String255EncryptedType as it is not needed anymore.
=> models: removal of String255EncryptedType

RELEASE-NOTES.rst, examples/app.py, invenio_oauth2server/translations/messages.pot, setup.cfg, setup.py, tests/conftest.py, tests/helpers.py, tests/test_decorators.py, tests/test_provider.py, tests/test_settings.py
* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).
=> global: inveniosoftware.org

invenio_oauth2server/views/server.py, setup.py, tests/conftest.py, tests/test_decorators.py, tests/test_server.py
* FIX Sets user identity when access token is used on the
REST API (closes #63).
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> views: user identity fix

invenio_oauth2server/forms.py, setup.py
* Updates forms to support Flask-WTF>=0.13. (Closes #82)
=> global: Flask-WTF upgrade to 0.13

AUTHORS.rst, invenio_oauth2server/config.py, invenio_oauth2server/ext.py, tests/conftest.py, tests/test_invenio_oauth2server.py, tests/test_provider.py
* Patches the `oauthlib.common.urlencoded` set of characters from the
application configuration, in order to gain control over special
characters in request query-strings.
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> global: oauthlib url encoded characters patch

invenio_oauth2server/views/settings.py, setup.py
* Fixes wrong form initialization allowing to support Flask-WTF 0.14.
(closes #105)
=> installation: unpin Flask-WTF

MANIFEST.in, examples/app.py, examples/templates/jwt.html, invenio_oauth2server/config.py, invenio_oauth2server/decorators.py, invenio_oauth2server/errors.py, invenio_oauth2server/ext.py, invenio_oauth2server/utils.py, setup.py, tests/conftest.py, tests/test_decorators.py
* Adds support for JWT (jwt.io), which is enabled by default. All the
protected endpoints ``require_api_auth`` will be automatically
check for JWT in the headers. A token can be generated by using the
``{{ jwt() }}`` context processor in jinja templates or from
``invenio_accounts.utils:jwt_create_token``. The generated token must
be sent by each request.
Signed-off-by: Harris Tzovanakis <me@drjova.com>
=> global: addition of JWT

invenio_oauth2server/views/settings.py
* ADDS check to delete the scopes field from the token form
so that it doesn't render if there are no scope choices.
(closes https://github.com/inveniosoftware/invenio-oauth2server/issues/121)
=> views: don't render scopes if empty

docs/conf.py, docs/examplesapp.rst, docs/index.rst, examples/app-fixtures.sh, examples/app.py, examples/consumer.py, invenio_oauth2server/alembic/4e57407b8e4a_add_on_delete_cascade.py, invenio_oauth2server/forms.py, invenio_oauth2server/templates/invenio_oauth2server/settings/index.html, invenio_oauth2server/templates/invenio_oauth2server/settings/token_permission_view.html, invenio_oauth2server/validators.py, invenio_oauth2server/views/server.py, invenio_oauth2server/views/settings.py, tests/test_settings.py, tests/test_validators.py
* Adds a view to see which authorization is garanted to a
application. (closes #139)
* Adds a client application as example. (closes #147)
=> views: show permissions associated to a token

docs/conf.py, docs/examplesapp.rst, docs/index.rst, examples/app.py, examples/consumer.py, invenio_oauth2server/alembic/4e57407b8e4a_add_on_delete_cascade.py, invenio_oauth2server/forms.py, invenio_oauth2server/validators.py, invenio_oauth2server/views/server.py
* Add example OAuth consumer application and required documentation to
demonstrate how to interact with invenio-oauth2server.
(closes #147) (closes #137)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
=> examples: integrate consumer example application

setup.py
* Unpin+bump flask-oauthlib version to fix AccessDenied errors
Versions 2.0.1 and 2.0.2 work fine.
AccessDenied errors were introduced in 2.0.3 and fixed in 2.0.5.
However, 2.0.5 contains breaking changes, hence 2.0.6.
(closes #163)
Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
=> Unpin+bump oauthlib to fix AccessDenied errors

invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/client_new.html, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/token_new.html
=> semantic: set `cancel` button style to default

invenio_oauth2server/forms.py, invenio_oauth2server/theme/semantic/form_styling.py
- fix the issue when we choose Client Type: Confidential or Public. 
- When a value is False, [wtforms](https://github.com/wtforms/wtforms/blob/c1906fbe37f137e9b79d499313432246400c69d5/wtforms/widgets/core.py#L69) doesnt render value="False" for the html elements.
- Fix the coerce for is_confidential, in html our values are strings, so when in python we do bool("False") we get True.
- changed hardcoded client_type to field.name
- closes #225
=> forms: fix for Client Type select

CHANGES.rst, invenio_oauth2server/version.py, setup.py, tests/conftest.py
closes #228 
includes release commit and changelog
CI has been broken for the last 5 months... installation takes forever locally (is been resolving for the las 40')
=> dependencies: restrict max version of wtforms

.github/workflows/tests.yml, docs/api.rst, invenio_oauth2server/errors.py, invenio_oauth2server/ext.py, run-tests.sh, setup.py
* Replaces `pkg_resources` with `importlib_metadata`.
* Fixes problems with sphinx build.
* Fixes JWTExtendedException get_headers function to work propperly with werkzeug.
=> ext: replace pkg_resources

.github/workflows/tests.yml, invenio_oauth2server/templates/semantic-ui/invenio_oauth2server/settings/helpers.html, tests/test_alembic.py
Removes the "secondary" styling from the new-buttons on the application page, and hides the icon in icon buttons for screen readers.
=> new-buttons: remove secondary class from buttons

invenio_oauth2server/views/settings.py
* closes https://github.com/zenodo/rdm-project/issues/480
Note: there's no proof that this will not result in timeout in the browser, as I couldn't reproduce the error locally. Should be tested in QA first
Previous generated SQL query:
```
SELECT 
oauth2server_token.id AS oauth2server_token_id,
oauth2server_token.client_id AS oauth2server_token_client_id, 
oauth2server_token.user_id AS oauth2server_token_user_id, 
oauth2server_token.token_type AS oauth2server_token_token_type, 
oauth2server_token.access_token AS oauth2server_token_access_token, 
oauth2server_token.refresh_token AS oauth2server_token_refresh_token, 
oauth2server_token.expires AS oauth2server_token_expires,
oauth2server_token._scopes AS oauth2server_token__scopes,
oauth2server_token.is_personal AS …
```
=> settings applications: simplify token queries

invenio_oauth2server/theme/semantic/form_styling.py
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2929
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
2. You agree that you …
=> fix: update iter_choices to include additional parameter in SelectSUI
